
### Universidad Autónoma de Chihuahua

#### Facultad de ingeniería

##### Ingeniería en Ciencias de la Computación


## Curso de Machine Learning
---


# Operaciones matriciales

##### **Trabajo de**: Adrian A. González Domínguez

###### **Matrícula**: 359834

##### **Asesor**: Manuel Alberto Chavez Salcido

##### *7 de septiembre de 2024*


### Librerias de codigo

In [72]:
import numpy
from scipy.linalg import lu

## Ejercicio 1: Creación de Vectores
**Objetivo:** Crear y manipular vectores en Python utilizando listas y la librería NumPy.

1. **Creación básica de vectores:**
   - Crea un vector de 5 elementos utilizando una lista en Python.
   - Convierte este vector en un array de NumPy.
   - Imprime el vector resultante y su tipo.

In [73]:
A1=[4,12,2,3,5]
A = numpy.array(A1)
print("Vector:", A)
print("Tipo:", type(A))

Vector: [ 4 12  2  3  5]
Tipo: <class 'numpy.ndarray'>


2. **Acceso y modificación de elementos:**
   - Accede al tercer elemento del vector y cámbialo por un nuevo valor.
   - Imprime el vector modificado.

In [74]:
A[2]=7
print(A)

[ 4 12  7  3  5]


3. **Operaciones con vectores:**
   - Crea dos vectores de 4 elementos.
   - Calcula la suma y la resta de los dos vectores.
   - Calcula el producto punto (dot product) de los dos vectores.
   - Encuentra la magnitud (norma) de uno de los vectores.

In [75]:
B1 = numpy.array([1,2,3,4])
B2 = numpy.array([11,12,13,14])
B3=B1+B2
B4=B1-B2
B5=B1.dot(B2)
B6=numpy.linalg.norm(B2)
print("B1:", B1)
print("B2:", B2)
print("B1+B2:", B3)
print("B1-B2:", B4)
print("B1·B2:", B5)
print("Magnitud de B1:", B6)


B1: [1 2 3 4]
B2: [11 12 13 14]
B1+B2: [12 14 16 18]
B1-B2: [-10 -10 -10 -10]
B1·B2: 130
Magnitud de B1: 25.099800796022265


## Ejercicio 2: Creación de Matrices
**Objetivo**: Crear y manipular matrices en Python.

1. **Creación básica de matrices:**
   - Crea una matriz 3x3 utilizando listas anidadas en Python.   
   - Convierte esta matriz en un array de NumPy.   
   - Imprime la matriz resultante y su forma (dimensión).

In [76]:
C1 = [[j + i*3 for j in range(3)] for i in range(3)]
C=numpy.array(C1)
print("Matriz:\n",C)
print("Forma:", C.shape)


Matriz:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
Forma: (3, 3)


2. **Acceso y modificación de elementos:**
   - Accede al elemento en la posición (2, 3) de una matriz 4x4.
   - Modifica este elemento y cambia la última fila de la matriz por un nuevo vector de 4 elementos.

In [77]:
D1 = [[j + i*4 for j in range(4)] for i in range(4)]
D=numpy.array(D1)
print("D:\n", D)
print("D[2][3]:", D[2][3])
D[2][3]=16
print("D[2][3]:", D[2][3])
D[3] = [i for i in range(4)]
print("D[3]:", D[3])
print("D:\n", D)


D:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
D[2][3]: 11
D[2][3]: 16
D[3]: [0 1 2 3]
D:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 16]
 [ 0  1  2  3]]


3. **Operaciones con matrices:**
   - Crea dos matrices 3x3 y realiza las siguientes operaciones:
   - Suma de matrices.
   - Resta de matrices.
   - Producto elemento a elemento (multiplicación Hadamard).
   - Multiplicación de matrices (producto matricial).
   - Calcula la transpuesta de una de las matrices.
   - Encuentra el determinante de una matriz 3x3.

In [78]:
E1 = numpy.array([[j + i*3 for j in range(3)] for i in range(3)])
E2 = numpy.array([[j + i*3 for j in range(2,-1,-1)] for i in range(2,-1,-1)])
E3=E1+E2
E4=E1-E2
E5=E1.dot(E2)
E6 = numpy.transpose(E1)
E7 = numpy.trace(E1)
print("E1:\n", E1)
print("E2:\n", E2)
print("E1+E2:\n", E3)
print("E1-E2:\n", E4)
print("E1·E2:\n", E5)
print("Transpuesta de E1:\n", E6)
print("Traza (determinante) de E1: ", E7)


E1:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
E2:
 [[8 7 6]
 [5 4 3]
 [2 1 0]]
E1+E2:
 [[8 8 8]
 [8 8 8]
 [8 8 8]]
E1-E2:
 [[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]
E1·E2:
 [[ 9  6  3]
 [54 42 30]
 [99 78 57]]
Transpuesta de E1:
 [[0 3 6]
 [1 4 7]
 [2 5 8]]
Traza (determinante) de E1:  12


## Ejercicio 3: Aplicación de Operaciones con Matrices
**Objetivo**: Aplicar operaciones matriciales a problemas más complejos.

1. **Multiplicación de matrices:**
   - Crea una matriz 2x3 y otra matriz 3x2. Realiza la multiplicación matricial y muestra el resultado.
   - Verifica si la multiplicación inversa da la matriz identidad.

In [79]:
F1 = numpy.array([[j + i*2 for j in range(3)] for i in range(2)])
F2 = numpy.array([[j + i*3 for j in range(2)] for i in range(3)])
F3 = F1.dot(F2)
print("F1:\n", F1)
print("F2:\n", F2)
print("Multiplicación de matrices -> F3=F1xF2:\n", F3)
F4 = numpy.linalg.inv(F3)
print("Inversa de F3 -> F3^-1:\n", F4)
F5=F3.dot(F4)
print("Matriz identidad -> F3xF3^-1:\n", F5)

F1:
 [[0 1 2]
 [2 3 4]]
F2:
 [[0 1]
 [3 4]
 [6 7]]
Multiplicación de matrices -> F3=F1xF2:
 [[15 18]
 [33 42]]
Inversa de F3 -> F3^-1:
 [[ 1.16666667 -0.5       ]
 [-0.91666667  0.41666667]]
Matriz identidad -> F3xF3^-1:
 [[ 1.00000000e+00  1.11022302e-15]
 [-2.22044605e-15  1.00000000e+00]]


2. **Sistemas de ecuaciones lineales:**

   - Utiliza la función np.linalg.solve() para resolver el sistema:
     
$$\begin{cases}
2x + 3y = 5 \\
4x + 5y = 6
\end{cases}$$


In [80]:
linear_system_1=[[2,3],[4,5]]
constant_linear_system_1=[5,6]
result=numpy.linalg.solve(linear_system_1,constant_linear_system_1)
print(result)

[-3.5  4. ]


3. **Descomposición de matrices:**
   - Realiza la descomposición de una matriz cuadrada en una matriz triangular superior e inferior (LU descomposición).
   - Utiliza la función np.linalg.inv() para encontrar la inversa de una matriz 3x3.

In [81]:
G = numpy.array([[4, 3, 2],
              [3, 2, 1],
              [2, 1, 3]])
P, L, U = lu(G)
G_inv = numpy.linalg.inv(G)
print("G:\n", G)
print("Matriz L triangular inferior de G: \n", L)
print("\nMatriz U triangular superior de G: \n", U)
print("\nMatriz P de permutación de G: \n", P)
print("Inversa de G -> G^-1: \n", G_inv)

G:
 [[4 3 2]
 [3 2 1]
 [2 1 3]]
Matriz L triangular inferior de G: 
 [[1.   0.   0.  ]
 [0.5  1.   0.  ]
 [0.75 0.5  1.  ]]

Matriz U triangular superior de G: 
 [[ 4.   3.   2. ]
 [ 0.  -0.5  2. ]
 [ 0.   0.  -1.5]]

Matriz P de permutación de G: 
 [[1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]
Inversa de G -> G^-1: 
 [[-1.66666667  2.33333333  0.33333333]
 [ 2.33333333 -2.66666667 -0.66666667]
 [ 0.33333333 -0.66666667  0.33333333]]


4. **Autovalores y autovectores:**
   - Calcula los autovalores y autovectores de una matriz 3x3.
   - Verifica que  $A \times v = \lambda \times v$, donde $A$ es la matriz, $v$ es el autovector y $\lambda$ es el autovalor correspondiente.

In [82]:
H = numpy.array([[4, 1, 2],
              [1, 3, 0],
              [2, 0, 3]])

eigenvalues, eigenvectors = numpy.linalg.eig(H)

print("Matriz:\n", H)
print("Autovalores:\n", eigenvalues)
print("Autovectores:\n", eigenvectors)


Matriz:
 [[4 1 2]
 [1 3 0]
 [2 0 3]]
Autovalores:
 [5.79128785 1.20871215 3.        ]
Autovectores:
 [[-7.80454320e-01 -6.25212808e-01 -3.97205465e-16]
 [-2.79603668e-01  3.49029782e-01 -8.94427191e-01]
 [-5.59207335e-01  6.98059565e-01  4.47213595e-01]]


In [83]:
# Verificar la relación A * v = λ * v
for i in range(len(eigenvalues)):
    eigenvalue = eigenvalues[i]
    eigenvector = eigenvectors[:, i]
    Hv = numpy.dot(H, eigenvector)
    lambda_v = eigenvalue * eigenvector

    print(f"Autovalor: {eigenvalue}")
    print(f"Autovector: {eigenvector}")
    print(f"H * v:\n{Hv}")
    print(f"λ * v:\n{lambda_v}")
    print(f"¿H * v = λ * v? {numpy.allclose(Hv, lambda_v)}\n")

Autovalor: 5.791287847477921
Autovector: [-0.78045432 -0.27960367 -0.55920734]
H * v:
[-4.51983562 -1.61926532 -3.23853065]
λ * v:
[-4.51983562 -1.61926532 -3.23853065]
¿H * v = λ * v? True

Autovalor: 1.2087121525220796
Autovector: [-0.62521281  0.34902978  0.69805956]
H * v:
[-0.75570232  0.42187654  0.84375308]
λ * v:
[-0.75570232  0.42187654  0.84375308]
¿H * v = λ * v? True

Autovalor: 2.9999999999999996
Autovector: [-3.97205465e-16 -8.94427191e-01  4.47213595e-01]
H * v:
[-9.99200722e-16 -2.68328157e+00  1.34164079e+00]
λ * v:
[-1.19161639e-15 -2.68328157e+00  1.34164079e+00]
¿H * v = λ * v? True

