In [17]:
import numpy

## Ejercicio 1: Creación de Vectores
**Objetivo:** Crear y manipular vectores en Python utilizando listas y la librería NumPy.

1. **Creación básica de vectores:**
   - Crea un vector de 5 elementos utilizando una lista en Python.
   - Convierte este vector en un array de NumPy.
   - Imprime el vector resultante y su tipo.

In [18]:
A1=[4,12,2,3,5]
A = numpy.array(A1)
print("Vector:", A)
print("Tipo:", type(A))

Vector: [ 4 12  2  3  5]
Tipo: <class 'numpy.ndarray'>


2. **Acceso y modificación de elementos:**
   - Accede al tercer elemento del vector y cámbialo por un nuevo valor.
   - Imprime el vector modificado.

In [19]:
A[2]=7
print(A)

[ 4 12  7  3  5]


3. **Operaciones con vectores:**
   - Crea dos vectores de 4 elementos.
   - Calcula la suma y la resta de los dos vectores.
   - Calcula el producto punto (dot product) de los dos vectores.
   - Encuentra la magnitud (norma) de uno de los vectores.

In [20]:
B1 = numpy.array([1,2,3,4])
B2 = numpy.array([11,12,13,14])
B3=B1+B2
B4=B1-B2
B5=B1.dot(B2)
B6=numpy.linalg.norm(B2)
print("B1:", B1)
print("B2:", B2)
print("B1+B2:", B3)
print("B1-B2:", B4)
print("B1·B2:", B5)
print("Magnitud de B1:", B6)


B1: [1 2 3 4]
B2: [11 12 13 14]
B1+B2: [12 14 16 18]
B1-B2: [-10 -10 -10 -10]
B1·B2: 130
Magnitud de B1: 25.099800796022265


## Ejercicio 2: Creación de Matrices
**Objetivo**: Crear y manipular matrices en Python.

1. **Creación básica de matrices:**
   - Crea una matriz 3x3 utilizando listas anidadas en Python.   
   - Convierte esta matriz en un array de NumPy.   
   - Imprime la matriz resultante y su forma (dimensión).

In [23]:
C1 = [[j + i*3 for j in range(3)] for i in range(3)]
C=numpy.array(C1)
print("Matriz:\n",C)
print("Forma:", C.shape)


Matriz:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
Forma: (3, 3)


2. **Acceso y modificación de elementos:**
   - Accede al elemento en la posición (2, 3) de una matriz 4x4.
   - Modifica este elemento y cambia la última fila de la matriz por un nuevo vector de 4 elementos.

In [33]:
D1 = [[j + i*4 for j in range(4)] for i in range(4)]
D=numpy.array(D1)
print("D:\n", D)
print("D[2][3]:", D[2][3])
D[2][3]=16
print("D[2][3]:", D[2][3])
D[3] = [i for i in range(4)]
print("D[3]:", D[3])
print("D:\n", D)


D:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
D[2][3]: 11
D[2][3]: 16
D[3]: [0 1 2 3]
D:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 16]
 [ 0  1  2  3]]


3. **Operaciones con matrices:**
   - Crea dos matrices 3x3 y realiza las siguientes operaciones:
   - Suma de matrices.
   - Resta de matrices.
   - Producto elemento a elemento (multiplicación Hadamard).
   - Multiplicación de matrices (producto matricial).
   - Calcula la transpuesta de una de las matrices.
   - Encuentra el determinante de una matriz 3x3.

In [42]:
E1 = numpy.array([[j + i*3 for j in range(3)] for i in range(3)])
E2 = numpy.array([[j + i*3 for j in range(2,-1,-1)] for i in range(2,-1,-1)])
E3=E1+E2
E4=E1-E2
E5=E1.dot(E2)
E6 = numpy.transpose(E1)
E7 = numpy.trace(E1)
print("E1:\n", E1)
print("E2:\n", E2)
print("E1+E2:\n", E3)
print("E1-E2:\n", E4)
print("E1·E2:\n", E5)
print("Transpuesta de E1:\n", E6)
print("Traza (determinante) de E1: ", E7)


E1:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
E2:
 [[8 7 6]
 [5 4 3]
 [2 1 0]]
E1+E2:
 [[8 8 8]
 [8 8 8]
 [8 8 8]]
E1-E2:
 [[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]
E1·E2:
 [[ 9  6  3]
 [54 42 30]
 [99 78 57]]
Transpuesta de E1:
 [[0 3 6]
 [1 4 7]
 [2 5 8]]
Traza (determinante) de E1:  12
